### ISSUE TITLE
p.293 うまくいくわけではありあません

### ISSUE THREAD

**Issue by kmuto** [ko1/uc_ja#2]
9月30日にオライリージャパンさまにはメールで報告したのですが、こちらでも報告申し上げます。

初版第1刷 9章 p.293 2段落目
うまくいくわけではありあません。→うまくいくわけではありません。

**Comment by ko1** [comment]
ありがとうございます。
もし訂正する機会があれば、させて頂きます。

**Comment by ko1** [comment]
2刷で対応しました。
